version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm ci --legacy-peer-deps
  build:
    commands:
      - echo Build started on `date`
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: public
